### ISSUE TITLE
Can't download encrypted files.

### ISSUE THREAD

**Issue by Asimina7** [eblocha/django-encrypted-files#1]
When I run it in development server with the runserver command, it works perfectly fine. But when I'm trying to run it in uwsgi it doesn't, and throws the following error
 " Alert! C:\Users\username\AppData\Local\Temp\YorOkjRs.docx.part could not be saved, because the source file could not be read.
Try again later, or contact the server administrator."

**Comment by eblocha** [comment]
What is throwing that error? Your browser, uwsgi, or the python app?

My suspicion is that uwsgi is configured to serve encrypted static or media files instead of passing it off the Django app. The request for any encrypted file has to hit the Django app in order to decrypt it first.

**Comment by ABakirtzis** [comment]
Hello eblocha, I am one of Asimina's colleagues, the error is thrown by the browser (can not read the file or can not parse response). We are using Django-rest-framework and we have an API endpoint that returns the file as a response, in that view other processes are being run that work (save the user that downloaded the file) so we know that the view is called and that uwsgi is not serving the media files. Is there another reason that this could happen, maybe something is not compatible with the default uwsgi configuration? 

Thank you in advance, and thank you for this great module!

**Comment by ABakirtzis** [comment]
We managed to solve the issue by adding the bellow option in the uwsgi file, can you explain why this is needed, regular files work fine for us through uwsgi.

wsgi-disable-file-wrapper = true

**Comment by eblocha** [comment]
Hi ABakirtzis, it looks like uWSGI uses the unix sendfile in its file_wrapper:

https://github.com/unbit/uwsgi/issues/1126#issuecomment-166687767

Sendfile is a kernel-level operation, so I believe the EncryptedFile class is completely skipped when reading the data, and it just sends the encrypted data from the file on disk.

So it appears that the only current solution is to disable the file_wrapper, unfortunately. There are some experimental kernel modules to use sendfile with AES encryption (https://github.com/kbeckmann/sendfile_aes), but they are not production-quality, or supported by uWSGI.

If you *really* need this optimization for regular files, you might look into hosting encrypted files on a separate application, or adding a wrapper class that converts the EncryptedFile class into io.BytesIO, which it appears is supported by uWSGI.
