### ISSUE TITLE
__init__() missing 1 required positional argument: 'backend'

### ISSUE THREAD

**Issue by mtbluedog** [eblocha/django-encrypted-files#3]
I don't know if this is a bug in my app or server (Ubuntu 20.04; Django 4.0.3; Python 3.8.10; Apache 2.4) or in `django-encrypted-files`. I followed the usage instructions to encrypt all uploaded files.

Using this in views.py:

```
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST,request.FILES)

        request_file = request.FILES['document'] if 'document' in request.FILES else None
        if request_file:
             fs = FileSystemStorage()
             file = fs.save(request_file.name, request_file)
             fileurl = fs.url(file)
```

Django debug output:

TypeError at /contact/contact/
__init__() missing 1 required positional argument: 'backend'

Environment:

Request Method: POST
Request URL: https://example.com/contact/contact/contact/

Django Version: 4.0.3
Python Version: 3.8.10
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'contactform.apps.ContactformConfig',
 'encrypted_files']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = middleware_method(
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/csrf.py", line 447, in process_view
    self._check_token(request)
  File "/usr/local/lib/python3.8/dist-packages/django/middleware/csrf.py", line 357, in _check_token
    request_csrf_token = request.POST.get("csrfmiddlewaretoken", "")
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/wsgi.py", line 101, in _get_post
    self._load_post_and_files()
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 369, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "/usr/local/lib/python3.8/dist-packages/django/http/request.py", line 319, in parse_file_upload
    return parser.parse()
  File "/usr/local/lib/python3.8/dist-packages/django/http/multipartparser.py", line 253, in parse
    handler.new_file(
  File "/usr/local/lib/python3.8/dist-packages/encrypted_files/uploadhandler.py", line 14, in new_file
    self.encryptor = Cipher(algorithms.AES(self.key),modes.CTR(self.nonce)).encryptor()

Exception Type: TypeError at /contact/contact/
Exception Value: __init__() missing 1 required positional argument: 'backend'

**Comment by eblocha** [comment]
Hello @mtbluedog, what version of cryptography is installed? I have tested with v36.0.1, and the `backend` argument is optional for the Cipher class (and appears to be ignored anyway).

From looking through their git history, it seems like the `backend` arg became optional after version 3.4.

**Comment by mtbluedog** [comment]
@eblocha thanks! My mistake; I didn't realize I was using an old version of cryptography. I had to force update it, and now it appears to work. You can delete this bug report, if needed.

The bigger picture is that I'm running a Python/Django web contact form with an optional file upload that sends encrypted email via the ProtonMail Bridge, and I'd like to encrypt the file via PGP and save it on the server.

It's a very broad question, but is your django-encrypted-files a good place to start by forking it? Would I need to change it to use the python-gnupg library instead of cryptography?

**Comment by eblocha** [comment]
@mtbluedog I think with PGP you might want to encrypt/decrypt client-side, right? So you wouldn't need any encryption logic on the server, you'd just treat everything as opaque byte data. If you do fork, you'll have to change just about all the code. This package is very small, it's just an upload handler that encrypts with AES, and a File wrapper that provides read, seek, and tell methods. These methods rely on the fact that it's AES in CTR mode.

**Comment by mtbluedog** [comment]
@eblocha Thanks, I'm pretty sure I don't want to encrypt in the browser with the contact form; I want to stream the file to the server and encrypt there, as you do with this library. I'll look into all that.

Do you have sample python code that runs in the python shell to decrypt a file? I'm trying to test the library and also have a way to decrypt files locally.

**Comment by eblocha** [comment]
@mtbluedog decrypting with cryptography is pretty simple:
```py
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes

decryptor = Cipher(
    algorithms.AES(key),
    modes.CTR(nonce),
).decryptor()

# read byte data from file...

# can call .update() multiple times for buffered decryption
decrypted = decryptor.update(bytes)

# for CTR mode, you don't need to call finalize, 
# but it is required for modes that do a data verification check, like GCM
decrypted += decryptor.finalize()

```

read more here:

https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/#cryptography.hazmat.primitives.ciphers.Cipher

**Comment by mtbluedog** [comment]
Thanks! I was able to test decryption of a file using this and it works.

```
openfile = open("encrypted.txt", 'rb')
read = openfile.read()
openfile.close()

# Separate IV and ciphertext; decrypt
iv = read[:16]
ciphertext = read[16:]
key = b'\x1a>\xf8\xcd\xe2\x8e_~V\x14\x98\xc2\x1f\xf9\xea\xf8\xd7c\xb3`!d\xd4\xe3+\xf7Q\x83\xb5~\x8f\xdd'
cipher = Cipher(algorithms.AES(key), modes.CTR(iv))
decryptor = cipher.decryptor()
decrypted = decryptor.update(ciphertext) + decryptor.finalize()

# Save decrypted file
savefile = open("decrypted.txt", "wb")
savefile.write(decrypted)
savefile.close()

```
